machine:
  timezone: Europe/Paris
  php:
    version: 7.1.0
  services:
   - mysql
  environment:
      APP_ENV: local
      APP_KEY: your_secret_key

dependencies:
  override:
    - composer install --prefer-source --no-interaction

test:
  override:
    - vendor/bin/phpunit
